# Healthcare & Medical – Chronic Disease Prediction using Machine Learning

## Machine Learning Pipeline

This notebook focuses on developing predictive machine learning models for Chronic Kidney Disease (CKD) using the cleaned healthcare dataset generated during the data analytics phase.

The notebook includes:
- Data Loading
- Data Preparation
- Feature Encoding
- Train-Test Split
- Logistic Regression
- Random Forest Classifier
- Model Evaluation
- Model Comparison
- Feature Importance
- Saving the Best Model

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import joblib

# Step 1: Load Cleaned Dataset

In [2]:
df = pd.read_csv("../data/processed/cleaned_chronic_disease_analysis.csv")

# Step 2: Dataset Overview

In [3]:
df.head()

,patient_id,age,gender,bmi,blood_pressure_systolic,blood_pressure_diastolic,serum_creatinine,blood_urea,egfr,albumin,...,hospital_visits_last_year,medications_count,ckd_stage,dialysis_required,kidney_transplant_history,ckd_diagnosis,high_bp,kidney_risk_score,senior_patient,comorbidity_count
0,1,24,Female,28.5,151,84,0.57,15.4,55.0,0,...,5,7,Stage 2,no,no,CKD,1,15.97,0,NaN
1,2,74,Female,27.9,112,100,1.98,63.9,51.8,5,...,6,8,Stage 4,no,no,CKD,0,65.88,1,NaN
2,3,65,Female,23.9,165,88,2.41,28.1,89.7,5,...,11,8,Stage 5,no,no,CKD,1,30.51,1,NaN
3,4,50,Female,31.7,182,62,0.56,46.8,59.5,4,...,5,6,Stage 4,no,no,CKD,1,47.36,0,NaN
4,5,49,Female,26.4,121,74,1.29,18.9,5.0,4,...,0,0,Stage 5,no,no,CKD,0,20.19,0,NaN

In [4]:
df.shape

(200000, 44)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 44 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   patient_id                 200000 non-null  int64
 1   age                        200000 non-null  int64
 2   gender                     200000 non-null  object
 3   bmi                        200000 non-null  float64
 4   blood_pressure_systolic    200000 non-null  int64
 5   blood_pressure_diastolic   200000 non-null  int64
 6   serum_creatinine           200000 non-null  float64
 7   blood_urea                 200000 non-null  float64
 8   egfr                       200000 non-null  float64
 9   albumin                    200000 non-null  int64
 10  hemoglobin                 200000 non-null  float64
 11  red_blood_cells            200000 non-null  object
 12  pus_cell                   200000 non-null  object
 13  pus_cell_clumps            200000 non-null  object
 14  bacteria                   200000 non-null  object
 15  blood_glucose_random       200000 non-null  int64
 16  sodium                     200000 non-null  float64
 17  potassium                  200000 non-null  float64
 18  calcium                    200000 non-null  float64
 19  phosphorus                 200000 non-null  float64
 20  diabetes_mellitus          200000 non-null  object
 21  hypertension               200000 non-null  object
 22  coronary_artery_disease    200000 non-null  object
 23  appetite                   200000 non-null  object
 24  pedal_edema                200000 non-null  object
 25  anemia                     200000 non-null  object
 26  smoking_status             200000 non-null  object
 27  alcohol_use                200000 non-null  object
 28  physical_activity          200000 non-null  object
 29  family_history_ckd         200000 non-null  object
 30  urine_protein              200000 non-null  float64
 31  urine_specific_gravity     200000 non-null  float64
 32  cholesterol                200000 non-null  int64
 33  heart_rate                 200000 non-null  int64
 34  hospital_visits_last_year  200000 non-null  int64
 35  medications_count          200000 non-null  int64
 36  ckd_stage                  200000 non-null  object
 37  dialysis_required          200000 non-null  object
 38  kidney_transplant_history  200000 non-null  object
 39  ckd_diagnosis              200000 non-null  object
 40  high_bp                    200000 non-null  int64
 41  kidney_risk_score          200000 non-null  float64
 42  senior_patient             200000 non-null  int64
 43  comorbidity_count          0 non-null       float64
dtypes: float64(13), int64(12), object(19)
memory usage: 67.1+ MB

# Step 3: Data Preparation

The dataset is prepared for machine learning by:

- Encoding categorical variables
- Separating features and target variable
- Preparing the data for model training

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_columns = df.select_dtypes(include=['object']).columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [7]:
df.head()

,patient_id,age,gender,bmi,blood_pressure_systolic,blood_pressure_diastolic,serum_creatinine,blood_urea,egfr,albumin,...,hospital_visits_last_year,medications_count,ckd_stage,dialysis_required,kidney_transplant_history,ckd_diagnosis,high_bp,kidney_risk_score,senior_patient,comorbidity_count
0,1,24,0,28.5,151,84,0.57,15.4,55.0,0,...,5,7,1,0,0,0,1,15.97,0,NaN
1,2,74,0,27.9,112,100,1.98,63.9,51.8,5,...,6,8,3,0,0,0,0,65.88,1,NaN
2,3,65,0,23.9,165,88,2.41,28.1,89.7,5,...,11,8,4,0,0,0,1,30.51,1,NaN
3,4,50,0,31.7,182,62,0.56,46.8,59.5,4,...,5,6,3,0,0,0,1,47.36,0,NaN
4,5,49,0,26.4,121,74,1.29,18.9,5.0,4,...,0,0,4,0,0,0,0,20.19,0,NaN

# Step 4: Feature Selection

Separate the independent variables (features) and dependent variable (target).

In [8]:
df.columns

Index(['patient_id', 'age', 'gender', 'bmi', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'serum_creatinine', 'blood_urea', 'egfr',
       'albumin', 'hemoglobin', 'red_blood_cells', 'pus_cell',
       'pus_cell_clumps', 'bacteria', 'blood_glucose_random', 'sodium',
       'potassium', 'calcium', 'phosphorus', 'diabetes_mellitus',
       'hypertension', 'coronary_artery_disease', 'appetite', 'pedal_edema',
       'anemia', 'smoking_status', 'alcohol_use', 'physical_activity',
       'family_history_ckd', 'urine_protein', 'urine_specific_gravity',
       'cholesterol', 'heart_rate', 'hospital_visits_last_year',
       'medications_count', 'ckd_stage', 'dialysis_required',
       'kidney_transplant_history', 'ckd_diagnosis', 'high_bp',
       'kidney_risk_score', 'senior_patient', 'comorbidity_count'],
      dtype='object')

# Step 5: Separate Features and Target

In [9]:
X = df.drop("ckd_diagnosis", axis=1)

y = df["ckd_diagnosis"]

# Step 6: Train-Test Split

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Step 7: Logistic Regression Model